### ISSUE TITLE
Audio desync when converting

### ISSUE THREAD

**Issue by fhtdtdj** [argorar/WebMConverter#17] opened 2022-08-10 21:52 UTC
Hi! Thanks for maintaining this fork.

I see this was already brought up by another user but got closed without follow-up.

Issue: tried converting a video recording with audio enabled but audio was desynced.

Re-encoding the source footage with another ffmpeg-using program, then converting the re-encoded file with Webmconverter results in properly synced audio (but at the cost of some video quality loss due to the first re-encode).

This occurred with footage recorded by Nvidia Geforce Experience. I have tested with other videos, which seem to get converted with audio properly synced. So it could be related to the codecs the Nvidia utility uses? I have included mediainfo codecs.

![2022-08-10 à 23 45 002 V 23-46-50 V 23-48-18](https://user-images.githubusercontent.com/88416370/184026695-9f1d691e-52a9-4ba5-a7a9-51a651e52ea1.jpg)

**Comment by argorar** [comment] 2022-08-15 15:21
I can't reply the issue  with a clip recorded by Nvidia Geforce Experience, the result is ok in my testing. Provide a clip in a free hosting service.

**Comment by oryxcallotis** [comment] 2022-08-16 00:22
Here's a webm that has the audio desync from a Shadowplay recording;

https://drive.google.com/file/d/1aRJr3tpUS1aiJ4fxNno5Lhmp5F-Jq8PD/view

And here's if I try a mp4 conversion (same thing happens);

https://drive.google.com/file/d/1eudpYsFNo4zCkAruQZ9MAWy5o827ko1Q/view

And here's the original Shadowplay clip if you want it (I set it to 5 minutes by default so it's a big file);

https://drive.google.com/file/d/1vlPZiLTcrxn9l0gi0RzcBNMrzKhkF_EL/view

---

Here's a webm conversion that has the audio synced properly;

https://drive.google.com/file/d/1loZ3WUi5Vx6Oo4jNSzTBurgsuH4oTaxl/view

And here's the original Shadowplay clip (I changed it to 15 seconds so I'm not uploading another huge file);

https://drive.google.com/file/d/1lTIrLLhiQIUxwnaMOD5283sEFE38WYpO/view

---

The audio desync happens maybe... 30-45% of the time. It only happens with certain .mp4 files, but when it does it happens every time you try to make a clip off them.

**Comment by oryxcallotis** [comment] 2022-08-16 00:23
log file for the first audio desynced webm:


```
Arguments for pass 1: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuv420p -threads 8 -slices 4 -metadata title="Street Fighter V 2022.08.13 - 10.31.35.19.DVR" -lag-in-frames 16 -auto-alt-ref 1 -ac 2 -c:a libopus -b:v 14392k -qcomp 0 -fs 15728640 -b:a 64k -tile-columns 1 -row-mt 1 -pass 1 -passlogfile "C:\Users\oryx\AppData\Local\Temp\063ea330-23f9-4ecd-95eb-f34028349501" -f webm -y "NUL"
Arguments for pass 2: -f nut -i pipe:0   -c:v libvpx-vp9 -pix_fmt yuv420p -threads 8 -slices 4 -metadata title="Street Fighter V 2022.08.13 - 10.31.35.19.DVR" -lag-in-frames 16 -auto-alt-ref 1 -ac 2 -c:a libopus -b:v 14392k -qcomp 0 -fs 15728640 -b:a 64k -tile-columns 1 -row-mt 1 -pass 2 -passlogfile "C:\Users\oryx\AppData\Local\Temp\063ea330-23f9-4ecd-95eb-f34028349501" -f webm -y "C:\Users\oryx\Desktop\Street Fighter V 2022.08.13 - 10.31.35.19.DVR.webm"
--- CREATING AVISYNTH PROXY --- 
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, nut, from 'pipe:0':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 59.94 fps, 59.90 tbr, 3833.71 tbn
  Stream #0:1: Audio: pcm_f32le (PFD  / 0x20444650), 48000 Hz, stereo, flt, 3072 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))
[libvpx-vp9 @ 000001b423603d80] v1.12.0-37-g7b65e4698
Output #0, webm, to 'NUL':
  Metadata:
    title           : Street Fighter V 2022.08.13 - 10.31.35.19.DVR
    encoder         : Lavf59.26.100
  Stream #0:0: Video: vp9, yuv420p(progressive), 1280x720, q=2-31, 14392 kb/s, 59.90 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.36.100 libvpx-vp9
    Side data:
      cpb: bitrate max/min/avg: 0/0/14392000 buffer size: 0 vbv_delay: N/A
frame=  470 fps=155 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    

frame=  511 fps=156 q=0.0 Lsize=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded 
--- FFMPEG HAS EXITED ---
--- ENTERING PASS 2 ---
--- CREATING AVISYNTH PROXY --- 
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, nut, from 'pipe:0':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 59.94 fps, 59.90 tbr, 3833.71 tbn
  Stream #0:1: Audio: pcm_f32le (PFD  / 0x20444650), 48000 Hz, stereo, flt, 3072 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))
  Stream #0:1 -> #0:1 (pcm_f32le (native) -> opus (libopus))
[libvpx-vp9 @ 00000280af4aeb00] v1.12.0-37-g7b65e4698
Output #0, webm, to 'C:\Users\oryx\Desktop\Street Fighter V 2022.08.13 - 10.31.35.19.DVR.webm':
  Metadata:
    title           : Street Fighter V 2022.08.13 - 10.31.35.19.DVR
    encoder         : Lavf59.26.100
  Stream #0:0: Video: vp9, yuv420p(progressive), 1280x720, q=2-31, 14392 kb/s, 59.90 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.36.100 libvpx-vp9
    Side data:
      cpb: bitrate max/min/avg: 0/0/14392000 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: opus, 48000 Hz, stereo, flt, 64 kb/s
    Metadata:
      encoder         : Lavc59.36.100 libopus
frame=  510 fps=5.5 q=10.0 size=   11264kB time=00:00:08.51 bitrate=10843.1kbits/s speed=0.0911x    

frame=  511 fps=5.4 q=17.0 Lsize=   15043kB time=00:00:08.55 bitrate=14413.0kbits/s speed=0.0896x    
video:14980kB audio:55kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.049479%
--- FFMPEG HAS EXITED ---

Video converted succesfully!

--- Final file size is 14.7 MB ---
```

**Comment by oryxcallotis** [comment] 2022-08-16 00:23
log file for the second clip that works fine;

```
Arguments for pass 1: -f nut -i pipe:0   -an -c:v libvpx-vp9 -pix_fmt yuv420p -threads 8 -slices 4 -metadata title="GGXXACPR_Win 2022.08.16 - 00.46.38.04.DVR" -lag-in-frames 16 -auto-alt-ref 1 -ac 2 -c:a libopus -b:v 15998k -qcomp 0 -fs 15728640 -b:a 64k -tile-columns 1 -row-mt 1 -pass 1 -passlogfile "C:\Users\oryx\AppData\Local\Temp\b37c76ec-260b-4122-914c-e16beaba3bdf" -f webm -y "NUL"
Arguments for pass 2: -f nut -i pipe:0   -c:v libvpx-vp9 -pix_fmt yuv420p -threads 8 -slices 4 -metadata title="GGXXACPR_Win 2022.08.16 - 00.46.38.04.DVR" -lag-in-frames 16 -auto-alt-ref 1 -ac 2 -c:a libopus -b:v 15998k -qcomp 0 -fs 15728640 -b:a 64k -tile-columns 1 -row-mt 1 -pass 2 -passlogfile "C:\Users\oryx\AppData\Local\Temp\b37c76ec-260b-4122-914c-e16beaba3bdf" -f webm -y "C:\Users\oryx\Desktop\GGXXACPR_Win 2022.webm"
--- CREATING AVISYNTH PROXY --- 
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, nut, from 'pipe:0':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 60 fps, 60 tbr, 61440 tbn
  Stream #0:1: Audio: pcm_f32le (PFD  / 0x20444650), 48000 Hz, stereo, flt, 3072 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))
[libvpx-vp9 @ 0000018c0b89dc00] v1.12.0-37-g7b65e4698
Output #0, webm, to 'NUL':
  Metadata:
    title           : GGXXACPR_Win 2022.08.16 - 00.46.38.04.DVR
    encoder         : Lavf59.26.100
  Stream #0:0: Video: vp9, yuv420p(progressive), 1280x720, q=2-31, 15998 kb/s, 60 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.36.100 libvpx-vp9
    Side data:
      cpb: bitrate max/min/avg: 0/0/15998000 buffer size: 0 vbv_delay: N/A
frame=  446 fps=222 q=0.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    

frame=  460 fps=221 q=0.0 Lsize=       1kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded 
--- FFMPEG HAS EXITED ---
--- ENTERING PASS 2 ---
--- CREATING AVISYNTH PROXY --- 
Guessed Channel Layout for Input Stream #0.1 : stereo
Input #0, nut, from 'pipe:0':
  Metadata:
    encoder         : Lavf56.40.101
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: rawvideo (I420 / 0x30323449), yuv420p, 1280x720, 60 fps, 60 tbr, 61440 tbn
  Stream #0:1: Audio: pcm_f32le (PFD  / 0x20444650), 48000 Hz, stereo, flt, 3072 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> vp9 (libvpx-vp9))
  Stream #0:1 -> #0:1 (pcm_f32le (native) -> opus (libopus))
[libvpx-vp9 @ 000001c851f2eb40] v1.12.0-37-g7b65e4698
Output #0, webm, to 'C:\Users\oryx\Desktop\GGXXACPR_Win 2022.webm':
  Metadata:
    title           : GGXXACPR_Win 2022.08.16 - 00.46.38.04.DVR
    encoder         : Lavf59.26.100
  Stream #0:0: Video: vp9, yuv420p(progressive), 1280x720, q=2-31, 15998 kb/s, 60 fps, 1k tbn
    Metadata:
      encoder         : Lavc59.36.100 libvpx-vp9
    Side data:
      cpb: bitrate max/min/avg: 0/0/15998000 buffer size: 0 vbv_delay: N/A
  Stream #0:1: Audio: opus, 48000 Hz, stereo, flt, 64 kb/s
    Metadata:
      encoder         : Lavc59.36.100 libopus
frame=  460 fps=7.5 q=8.0 size=   12288kB time=00:00:07.67 bitrate=13124.3kbits/s speed=0.125x    

frame=  460 fps=7.3 q=12.0 Lsize=   14751kB time=00:00:07.69 bitrate=15714.3kbits/s speed=0.122x    
video:14696kB audio:49kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.044905%
--- FFMPEG HAS EXITED ---

Video converted succesfully!

--- Final file size is 14.4 MB ---
```

**Comment by fhtdtdj** [comment] 2022-08-17 01:01
> I can't reply the issue with a clip recorded by Nvidia Geforce Experience, the result is ok in my testing. Provide a clip in a free hosting service.

[Test recording source](https://www.mediafire.com/file/dhqll0976tzavgo/Test_Video_Source.mp4/file)

[Test recording converted webm with desync audio](https://www.mediafire.com/file/k20onf14xhbufg5/Test_Video_Converted_Webm_Desync_Audio.webm/file)

**Comment by argorar** [comment] 2022-08-17 02:34
This is probably caused for an external library [see issue here](https://github.com/FFMS/ffms2/issues/216#issuecomment-122969384). The latest compatible versions still doesn't fix the problem with these specifics codecs.

**Comment by 9Pierre** [comment] 2022-08-27 10:12
I began to have the the same audio issue about a month ago maybe, but with any youtube video that comes in mkv, the desync does not happen if I convert said mkv file to mp4 or if it comes from youtube already in mp4.

**Comment by oryxcallotis** [comment] 2022-08-30 20:24
> This is probably caused for an external library [see issue here](https://github.com/FFMS/ffms2/issues/216#issuecomment-122969384). The latest compatible versions still doesn't fix the problem with these specifics codecs.

I'm not sure if I'm allowed to link files on here, but I tried copy-pasting the ffms2.dll file from my (really) old version of WebmForR... into your branch and... The audio desync problem seems to be gone? I tried it with that Street Fighter 5 video I linked above and it's all synced up fine, and I have the added benefit of converting to mp4 that this version has (along with generally being faster).

If anyone's interested in trying for themselves, backup your current version of ffms2.dll and try using this version instead;

https://drive.google.com/file/d/1sVNtVFyIAnGs1ugBrHO1vdLoK5kWX1nb/view?usp=sharing

The clips I make from this now all synced up;

https://drive.google.com/file/d/1bFvsgAoeGTggOGzNZ9af_-1vCAtrJHym/view?usp=sharing

**Comment by argorar** [comment] 2022-08-31 00:10
I tried that  with the GTA video and crashed.

**Comment by fhtdtdj** [comment] 2022-08-31 11:04
Getting an error too (not finding any audio tracks when opening the file) with the dll you uploaded.

Tried with a couple older ffms2.dll I found from other installs, and desync still occurs.

**Comment by argorar** [comment] 2022-09-05 04:13
Guys, update to the latest version 3.18.6. All my test worked fine and the problem is solve.

**Comment by fhtdtdj** [comment] 2022-09-05 08:58
Awesome, problem seems fixed on my side as well.

How did you resolve the issue?

**Comment by argorar** [comment] 2022-09-06 04:00
Separating responsibilities. These third -party libraries are very inconsistent.

I proceed to close the issue.

**Closed by argorar** 2022-09-06 04:00 UTC
